version: "3.8"

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
    ports:
      - protocol: tcp
        published: 8080
        target: 80
    volumes:
      - "./nginx-example:/data/db"
  mongodb-example:
    container_name: mongodb1
    image: mongo:latest
    ports:
      - protocol: tcp
        published: 27019
        target: 27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: eko
      MONGO_INITDB_ROOT_PASSWORD: eko
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db"
  redis-example:
    container_name: redis-example
    image: redis:latest
    ports:
      - protocol: tcp
        published: 6379
        target: 6379
    volumes:
      - "./redis:/data/db"
